version: "3.5"

services:
  ctrl-money:
    tty: true
    stdin_open: true
    # env_file: envs/global-secret.env
    image: node:$NODE_VERSION
    working_dir: /app
    command: make startup
    ports:
      - 5031:5031
    volumes:
      - ./:/app
      - ctrl-money-node-modules:/app/node_modules

volumes:
  ctrl-money-node-modules:
