version: "3.5"

services:
  online-tabletop:
    tty: true
    stdin_open: true
    network_mode: host
    # env_file: envs/global-secret.env
    image: node:$NODE_VERSION
    working_dir: /app
    command: make startup
    ports:
      - 5031:5031
    volumes:
      - user-home:/root
      - ./:/app:cached
      - ./node_modules:/app/node_modules:delegated

volumes:
  user-home:
